BEGIN;

ALTER TABLE IF EXISTS package
    RENAME COLUMN IF EXISTS volume TO height;

ALTER TABLE IF EXISTS package
    ADD COLUMN IF NOT EXISTS widht INT DEFAULT 1,
    ADD COLUMN IF NOT EXISTS depth INT DEFAULT 1;

COMMIT;